# Generated by Django 4.0.1 on 2022-01-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=5000, null=True)),
                ('number', models.CharField(max_length=30, null=True)),
                ('msg_date', models.DateField(null=True)),
                ('is_read', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(max_length=5000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('shifting_loc', models.CharField(max_length=200, null=True)),
                ('brief_items', models.CharField(max_length=300, null=True)),
                ('items', models.CharField(max_length=5000, null=True)),
                ('professional', models.CharField(max_length=200, null=True)),
                ('requestdate', models.DateField(null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('updationdate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
