# Generated by Django 4.0.1 on 2022-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpmanagement', '0002_remove_siteuser_professional_remove_siteuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='shiftingdate',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
